name: vtm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.2.2
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.8.18
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.9.0
  - pip:
    - open3d==0.18.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - plyfile
    - opencv-python
    - rembg[gpu,cli]
    - progressbar2
    - gdown
    - gitpython
    - git+https://github.com/cheind/py-thin-plate-spline
    - hickle
    - tensorboard
    - numpy==1.24.1
    - PyQt5
    - Cython
    - scipy==1.10.1
    - scikit-learn==1.2.2
    - transformers==4.26.1
    - dataclasses==0.6
    - filelock==3.12.3
    - requests==2.28.1
    - uvicorn==0.22.0
    - fastapi==0.98.0
    - pydantic==1.10.9
    - starlette==0.27.0
    - psutil==5.9.5
    - packaging==23.0
    - sacremoses==0.0.53
    - h5py==3.10.0
    - tokenizers==0.13.2
    - regex==2022.10.31
    - sentencepiece==0.1.99
    - six==1.16.0
    - nltk==3.8.1
    - pillow==9.5.0
    - pympler==1.0.1
    - textblob==0.17.1
    - clip @ git+https://github.com/openai/CLIP.git@a9b1bf5920416aaeaec965c25dd9e8f98c864f16
